---
- name: Install common packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
  with_items: packages
  sudo: yes

- name: Download Agent
  get_url:
    url: https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh
    dest: ~/install_agent.sh
    mode: 0700
  register: dlagent


- shell: 'DD_API_KEY={{ddapikey}} bash -c "~/install_agent.sh"'
  when: dlagent|changed

- lineinfile:
    dest: /etc/dd-agent/datadog.conf
    regexp: "^#tags: mytag0, mytag1"
    line: 'tags: demohost:ec2'
  remote_user: ec2-user
  sudo: yes
  when: dlagent|changed
