# Main tasks for all hosts
- name: Check if Docker_Common already processed
  raw: stat $HOME/.dockercommon
  register: need_docker_common
  ignore_errors: True



- datadog_event:
    title: "Performing Docker Common Tasks: {{inventory_hostname}}"
    priority: "normal"
    alert_type: "warning"
    tags: "DDDemoEvent"
    text: "Initiated from Ansible"
    api_key: "{{ ddapikey }}"
  when: need_docker_common|failed

- include_vars: demovars.yml
  when: need_docker_common|failed
- include: hostname.yml
  when: need_docker_common|failed
- include: sudoers.yml
  when: need_docker_common|failed
- include: packages.yml
  when: need_docker_common|failed

- file:
    path: ~/.dockercommon
    state: touch
  when: need_docker_common|failed
